---
title: "Data Visualization with ggplot2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Prerequisites
Load the tidyverse.

```{r}
library(tidyverse)
```

## Load mpg data
I am putting it into a df called mpg and using ?mpg to get an idea of the structure.

```{r}
mpg<-mpg
?mpg
```

## First Basic Plots

Displacement vs hwy mpg
```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

Hwy mpg vs displacement
```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = hwy, y = cyl))
```

Class vs drv
```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = class, y = drv))
```

Displacement vs hwy mpg colored by class
```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color=class))
```

Displacement vs hwy mpg scaled by size, alpha, shape, and color
```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size=class))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha=class))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape=class))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color="blue")
```

## Faceting



